[Definition]
failregex = ^.*postscreen\[\d+\]: PREGREET \d+ after [\d.]+ from \[<HOST>\]:\d+
            ^.*postscreen\[\d+\]: HANGUP after [\d.]+ from \[<HOST>\]:\d+ in tests (before|after) SMTP handshake
            ^.*postscreen\[\d+\]: DNSBL rank \d+ for \[<HOST>\]:\d+
            ^.*postscreen\[\d+\]: COMMAND (PIPELINING|TIME LIMIT|COUNT LIMIT|LENGTH LIMIT) from \[<HOST>\]:\d+
            ^.*postscreen\[\d+\]: NON-SMTP COMMAND from \[<HOST>\]:\d+
            ^.*postscreen\[\d+\]: BARE NEWLINE from \[<HOST>\]:\d+

ignoreregex =

journalmatch =
