name: simply-mailserver

networks:
  mail:
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/24

services:
  mariadb:
    extends:
      file: ./docker/services/mariadb.yml
      service: mariadb

  redis:
    extends:
      file: ./docker/services/redis.yml
      service: redis

  clamav:
    extends:
      file: ./docker/services/clamav.yml
      service: clamav

  opendkim:
    extends:
      file: ./docker/services/opendkim.yml
      service: opendkim

  opendmarc:
    extends:
      file: ./docker/services/opendmarc.yml
      service: opendmarc

  rspamd:
    extends:
      file: ./docker/services/rspamd.yml
      service: rspamd

  dovecot:
    extends:
      file: ./docker/services/dovecot.yml
      service: dovecot

  postfix:
    extends:
      file: ./docker/services/postfix.yml
      service: postfix

  fail2ban:
    extends:
      file: ./docker/services/fail2ban.yml
      service: fail2ban

  phpmyadmin:
    extends:
      file: ./docker/services/phpmyadmin.yml
      service: phpmyadmin

  manager-api:
    extends:
      file: ./docker/services/manager-api.yml
      service: manager-api

  deliverability-probe:
    extends:
      file: ./docker/services/deliverability-probe.yml
      service: deliverability-probe

  manager-ui:
    extends:
      file: ./docker/services/manager-ui.yml
      service: manager-ui
