services:
  simply-mailserver:
    stdin_open: true
    tty: true
    restart: always
    container_name: simply-mailserver
    build:
      context: .
    env_file: .env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4000:4000" # admin web application
      - "4001:4001" # rspamd web interface
      - "4002:4002" # phpmyadmin
      - "4003:3000" # nest api secure only
      - "4080:4080" # roundcube unsecure
      # - "4190:4190" # could be useful in the case of an external e-mail client
      - "4443:4443" # roundcube secure
    extra_hosts:
      - "${DOMAIN_FQDN}:${ADRESSIP}"
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.200.0.20
    volumes:
      - $DOCKER_VOLUMES/log:/var/log
      - $DOCKER_VOLUMES/ssl:/etc/_private
      - $DOCKER_VOLUMES/mail:/var/mail
      - $DOCKER_VOLUMES/mysql:/var/lib/mysql
      - $DOCKER_VOLUMES/postfix:/var/spool/postfix
      - $DOCKER_VOLUMES/custom_rules:/var/_custom_rules
      - $DOCKER_VOLUMES/redis:/var/lib/redis
      - $DOCKER_VOLUMES/rspamd:/var/lib/rspamd
      - $DOCKER_VOLUMES/clamav:/var/lib/clamav
      - $DOCKER_VOLUMES/opendkim:/etc/opendkim
      - $DOCKER_VOLUMES/fail2ban:/var/lib/fail2ban
      - $DOCKER_VOLUMES/opendmarc:/var/opendmarc

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.200.0.0/16"
          gateway: "172.200.0.1"
