#!/usr/bin/env bash
# Infrastructure: container state, healthchecks, mariadb schema + triggers,
# host-exposed and bridge-only network ports.

t_containers_healthy() {
  section "Infrastructure"
  for c in "${HEALTH_CONTAINERS[@]}"; do
    local s; s=$(docker inspect -f '{{.State.Health.Status}}' "$c" 2>/dev/null || echo missing)
    [[ "$s" == "healthy" ]] && pass "health.$c" "healthy" || fail "health.$c" "$s"
  done
  for c in "${STACK_CONTAINERS[@]}"; do
    local s; s=$(docker inspect -f '{{.State.Status}}' "$c" 2>/dev/null || echo missing)
    [[ "$s" == "running" ]] && pass "running.$c" "running" || fail "running.$c" "$s"
  done
}

t_redis_pong() {
  local r; r=$(redis_get PING)
  assert_eq "redis.ping" "PONG" "$r"
}

t_clamav_responds() {
  local r; r=$(docker exec mail-clamav sh -c 'echo PING | nc -w 2 127.0.0.1 3310' 2>/dev/null | tr -d '\0\n')
  assert_eq "clamav.ping" "PONG" "$r"
}

t_mariadb_schema() {
  local tables
  tables=$(docker exec mail-mariadb mariadb -uroot -p"$DB_ROOT_PASSWORD" -BN mailserver -e "SHOW TABLES" 2>/dev/null | sort | tr '\n' ' ')
  for t in accounts dkim_keys refresh_tokens sieve_reject_senders virtual_aliases virtual_domains virtual_quota_domains virtual_quota_users virtual_users; do
    case " $tables " in
      *" $t "*) pass "db.table.$t" "present" ;;
      *)        fail "db.table.$t" "missing (have: $tables)" ;;
    esac
  done
  local trig_count
  trig_count=$(docker exec mail-mariadb mariadb -uroot -p"$DB_ROOT_PASSWORD" -BN mailserver -e "SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA = 'mailserver'" 2>/dev/null)
  [[ "${trig_count:-0}" -ge 5 ]] && pass "db.quota_triggers" "count=$trig_count" || fail "db.quota_triggers" "count=$trig_count (expected >=5)"
}

# The dkim_keys table must carry one row per (domain, selector) once the
# install.sh DKIM step ran (and equally after `POST /api/v1/domains`).
# The previous suite only checked the table existed -- a row count of 0
# was indistinguishable from a healthy state, masking the regression where
# the DKIM material was generated by the opendkim sidecar but never
# persisted into the manager-api DB.
t_dkim_keys_populated() {
  local sql="docker exec mail-mariadb mariadb -uroot -p${DB_ROOT_PASSWORD} -BN mailserver"
  local count
  count=$($sql -e "SELECT COUNT(*) FROM dkim_keys WHERE domain = '$TEST_DOMAIN'" 2>/dev/null)
  if [[ "${count:-0}" -ge 1 ]]; then
    pass "db.dkim_keys.populated" "row_count=$count for $TEST_DOMAIN"
  else
    fail "db.dkim_keys.populated" "no row for $TEST_DOMAIN (sidecar key never persisted)"
    return
  fi
  # Sanity-check the persisted shape: selector + dns_name + non-empty
  # public_key + txt_record that actually contains a DKIM `p=` segment.
  local bad
  bad=$($sql -e "SELECT COUNT(*) FROM dkim_keys WHERE domain = '$TEST_DOMAIN' AND (selector = '' OR dns_name = '' OR public_key = '' OR txt_record NOT LIKE '%p=%')" 2>/dev/null)
  if [[ "${bad:-0}" -eq 0 ]]; then
    pass "db.dkim_keys.shape" "selector + dns_name + public_key + txt_record(p=...) all populated"
  else
    fail "db.dkim_keys.shape" "$bad row(s) with empty/invalid columns"
  fi
}

t_ports_open() {
  section "Network surface"
  for port in 25 465 587 993; do
    if timeout 3 bash -c "exec 3<>/dev/tcp/127.0.0.1/$port" 2>/dev/null; then
      pass "tcp.$port" "open"
    else
      fail "tcp.$port" "closed"
    fi
  done
  # 4190 (ManageSieve) is bridge-only. Probe it from inside dovecot, which
  # is always present; the previous bridge-via-roundcube probe broke when
  # the webmail overlay is not deployed.
  if docker exec mail-dovecot sh -c 'echo | nc -z 127.0.0.1 4190' >/dev/null 2>&1; then
    pass "tcp.4190.bridge" "open (local)"
  else
    fail "tcp.4190.bridge" "closed"
  fi
}

t_containers_healthy
t_redis_pong
t_clamav_responds
t_mariadb_schema
t_dkim_keys_populated
t_ports_open
