ssl      = yes
ssl_cert = </etc/letsencrypt/live/${TLS_CERT_NAME}/fullchain.pem
ssl_key  = </etc/letsencrypt/live/${TLS_CERT_NAME}/privkey.pem
ssl_dh   = </etc/dovecot/dh.pem
ssl_min_protocol = TLSv1.2
ssl_cipher_list  = HIGH:!aNULL:!MD5:!3DES:!CAMELLIA:!ARIA:!RC4:!SHA
ssl_prefer_server_ciphers = yes
