protocol lda {
  mail_plugins = $mail_plugins sieve quota
  postmaster_address = postmaster@${MAIL_HOSTNAME}
}

protocol lmtp {
  mail_plugins = $mail_plugins sieve quota
  postmaster_address = postmaster@${MAIL_HOSTNAME}
}
