plugin {
  sieve         = file:~/sieve;active=~/.dovecot.sieve
  sieve_default = /var/lib/dovecot/sieve/global/default.sieve
  sieve_after   = /var/lib/dovecot/sieve/global/spam-to-junk.sieve
  sieve_extensions = +editheader +relational +comparator-i;ascii-numeric
  sieve_max_script_size   = 1M
  sieve_quota_max_scripts = 5
  sieve_quota_max_storage = 1M
}
