services:
  mailserver:
    stdin_open: true
    tty: true
    restart: always
    container_name: simply-mailserver
    build:
      context: .
      args:
        DOMAIN_FQDN: ${DOMAIN_FQDN}
    env_file: .env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4000:80"
      - "4001:3000"
      - "4080:4080"
      - "4190:4190"
      - "4443:4443"
    extra_hosts:
      - "${DOMAIN_FQDN}:${ADRESSIP}"
    volumes:
      - ./volumes/log:/var/_log
      - ./volumes/ssl:/etc/_private
      - ./volumes/mail:/var/mail
      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/postfix:/var/spool/postfix
