[Definition]
actionstart = /usr/local/bin/mailserver-chain.sh start <name>
actionstop = /usr/local/bin/mailserver-chain.sh stop <name>
actioncheck = /usr/local/bin/mailserver-chain.sh check <name>
actionban = /usr/local/bin/mailserver-chain.sh ban <name> <ip>
actionunban = /usr/local/bin/mailserver-chain.sh unban <name> <ip>

[Init]
