[Definition]
actionstart = /usr/local/bin/roundcube-deny.sh start <name>
actionstop = /usr/local/bin/roundcube-deny.sh stop <name>
actioncheck =
actionban = /usr/local/bin/roundcube-deny.sh ban <name> <ip>
actionunban = /usr/local/bin/roundcube-deny.sh unban <name> <ip>

[Init]
