server:
    username: "unbound"
    chroot: ""
    directory: "/etc/unbound"
    pidfile: ""
    verbosity: 0
    use-syslog: no
    logfile: ""
    log-queries: no

    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: 172.200.0.0/24 allow

    trust-anchor-file: "/usr/share/dnssec-root/trusted-key.key"
    qname-minimisation: yes
    prefetch: yes
    hide-identity: yes
    hide-version: yes

    num-threads: 1
    msg-cache-size: 16m
    rrset-cache-size: 32m

remote-control:
    control-enable: yes
    control-interface: /run/unbound.control.sock
