clamav {
  symbol = "CLAM_VIRUS";
  type = "clamav";
  log_clean = true;
  servers = "mail-clamav:3310";
  scan_mime_parts = true;
  scan_text_mime = false;
  scan_image_mime = false;
  max_size = 31457280;
  action = "reject";
  message = '${SCANNER}: virus found: "${VIRUS}"';
}
