Syslog                  no
SyslogSuccess           no
LogWhy                  yes

Socket                  inet:8891@0.0.0.0
PidFile                 /var/run/opendkim/opendkim.pid
UserID                  opendkim:opendkim
Mode                    sv
Canonicalization        relaxed/simple
MinimumKeyBits          1024

KeyTable                /etc/opendkim/key.table
SigningTable            refile:/etc/opendkim/signing.table

ExternalIgnoreList      /etc/opendkim/trusted.hosts
InternalHosts           /etc/opendkim/trusted.hosts
TrustAnchorFile         /etc/opendkim/trusted.hosts

OversignHeaders         From
AutoRestart             yes
AutoRestartRate         10/1M
SignatureAlgorithm      rsa-sha256
