services:
  opendmarc:
    container_name: mail-opendmarc
    restart: unless-stopped
    build:
      context: ../../images/opendmarc
    env_file: ../../.env
    volumes:
      - ${VOLUMES_PATH}/opendmarc:/var/lib/opendmarc
    networks:
      mail:
        ipv4_address: 172.200.0.14
    dns:
      - 172.200.0.9
    depends_on:
      unbound:
        condition: service_started
      mariadb:
        condition: service_healthy
