services:
  rspamd:
    container_name: mail-rspamd
    restart: unless-stopped
    build:
      context: ../../images/rspamd
    env_file: ../../.env
    volumes:
      - ${VOLUMES_PATH}/rspamd:/var/lib/rspamd
    networks:
      mail:
        ipv4_address: 172.200.0.15
    depends_on:
      redis:
        condition: service_healthy
      clamav:
        condition: service_healthy
    ports:
      - "${BINDING_IP_RSPAMD_UI}:${BINDING_PORT_RSPAMD_UI}:11334"
