services:
  unbound:
    container_name: mail-unbound
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: ../../images/unbound
    networks:
      mail:
        ipv4_address: 172.200.0.9
