Socket                  inet:8893@0.0.0.0
PidFile                 /var/run/opendmarc/opendmarc.pid
AuthservID              ${MAIL_HOSTNAME}
TrustedAuthservIDs      ${MAIL_HOSTNAME}

PublicSuffixList        /var/lib/opendmarc/public_suffix_list.dat
HistoryFile             /var/lib/opendmarc/opendmarc.dat
IgnoreHosts             /var/lib/opendmarc/ignore.hosts

UserID                  opendmarc:opendmarc
UMask                   0002

AutoRestart             yes
AutoRestartRate         10/1M
Syslog                  no
SyslogFacility          mail

SPFSelfValidate         true
RejectFailures          ${DMARC_REJECT_FAILURES}
FailureReports          false
